services:
  vscode:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - node-modules:/workspace/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql-dev
      - postgres-dev
      - sqlite-dev
    networks:
      - dev-network

  # MySQL開発環境
  mysql-dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - dev-network
    restart: unless-stopped

  # PostgreSQL開発環境
  postgres-dev:
    image: postgres:16
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - dev-network
    restart: unless-stopped

  # SQLite開発環境（ファイルベース）
  sqlite-dev:
    image: alpine:latest
    command: tail -f /dev/null
    volumes:
      - sqlite-dev-data:/data
    networks:
      - dev-network

volumes:
  mysql-dev-data:
  postgres-dev-data:
  sqlite-dev-data:
  node-modules:

networks:
  dev-network:
    driver: bridge